### ISSUE TITLE
Error Running Test Data 

### ISSUE THREAD

**Issue by frankmartiniv** [fmfi-compbio/warpstr#6]
Hello,
I am new to programming, and when trouble shooting the following error, I was unsure whether or not it was due to my input fai file or the program. Any guidance would be appreciated.

![Screenshot 2023-07-26 133505](https://github.com/fmfi-compbio/warpstr/assets/140645516/24e154c2-1526-4919-be8a-bab48b4e9278)

**Comment by xsitarcik** [comment]
Hello,
please, check your input reference FASTA file. Are there chromosomes listed as `chr#`, i.e.  `chr4` ? Some references list chromosomes simply as `#` without the `chr` prefix, check if that is your case. Then, adjust the config file so the **loci coordinates match the chromosome naming in your reference**. 

Simply open the config file and locate the `loci`->`coord` element, you used the template config so it should be looking like this:
```yaml
...
loci:
  - name: Human_STR_1108232
    coord: chr4:183178378-183178421
...
```
Adjust the `coord` element appropriately, in case of listing chromosomes as `#` replace `chr4` with just `4`, so it would like this:
```yaml
...
loci:
  - name: Human_STR_1108232
    coord: 4:183178378-183178421
...
```
